#!/usr/bin/env bash
# inchambers-gateway — one-liner installer for self-hosted docker deployments.
#
# Usage (from the firm's target VM as a user with docker access):
#   curl -fsSL https://raw.githubusercontent.com/inchambers-ai/inchambers/main/gateway/deploy/docker-compose/install.sh | bash
#
# What it does:
#   1. Verifies docker + docker compose are available.
#   2. Clones the compose file + Caddyfile to /opt/inchambers-gateway (or $IC_GATEWAY_DIR).
#   3. Prompts for: inchambers.ai org UUID, gateway domain, OpenRouter key
#      (optional), admin email.
#   4. Generates a 32-byte master key + LiteLLM key locally (never leaves
#      the box).
#   5. Writes .env, pulls the 4 images, runs `docker compose up -d`.
#   6. Prints the gateway URL to paste into your inchambers.ai org admin
#      dashboard (Settings → AI Platform → Gateway URL).

set -euo pipefail

readonly BRANCH="${IC_GATEWAY_BRANCH:-main}"
readonly REPO_RAW="https://raw.githubusercontent.com/inchambers-ai/inchambers/${BRANCH}/gateway"
readonly INSTALL_DIR="${IC_GATEWAY_DIR:-/opt/inchambers-gateway}"
readonly IMAGE_REGISTRY="${IC_GATEWAY_REGISTRY:-ghcr.io/inchambers-ai}"
readonly IMAGE_TAG="${IC_GATEWAY_TAG:-latest}"

C_BOLD=$(printf '\033[1m'); C_DIM=$(printf '\033[2m'); C_GREEN=$(printf '\033[32m')
C_YELLOW=$(printf '\033[33m'); C_RED=$(printf '\033[31m'); C_RESET=$(printf '\033[0m')

log()   { printf '%s\n' "${C_BOLD}==>${C_RESET} $*"; }
warn()  { printf '%s\n' "${C_YELLOW}warning:${C_RESET} $*" >&2; }
die()   { printf '%s\n' "${C_RED}error:${C_RESET} $*" >&2; exit 1; }
hint()  { printf '%s\n' "${C_DIM}   $*${C_RESET}"; }

# ─── Pre-flight ────────────────────────────────────────────────────────────
check_prereqs() {
  log "Checking prerequisites"
  command -v docker >/dev/null 2>&1 || die "docker not found — install Docker first"
  docker compose version >/dev/null 2>&1 || die "docker compose v2 not found (run 'docker compose version' to verify)"
  command -v curl >/dev/null 2>&1 || die "curl not found"
  command -v openssl >/dev/null 2>&1 || die "openssl not found (needed to generate the master key)"
  docker info >/dev/null 2>&1 || die "can't talk to the docker daemon — are you in the docker group?"
}

# ─── Inputs ────────────────────────────────────────────────────────────────
prompt() {
  local varname="$1" prompt_text="$2" default="${3:-}"
  local value=""
  if [[ -n "$default" ]]; then
    read -r -p "${prompt_text} [${default}]: " value
    value="${value:-$default}"
  else
    while [[ -z "$value" ]]; do
      read -r -p "${prompt_text}: " value
    done
  fi
  printf -v "$varname" '%s' "$value"
}

prompt_secret() {
  local varname="$1" prompt_text="$2"
  local value=""
  read -r -s -p "${prompt_text}: " value
  echo
  printf -v "$varname" '%s' "$value"
}

collect_inputs() {
  log "Collecting configuration (nothing leaves this host)"

  prompt        GATEWAY_ORG_ID   "inchambers.ai org UUID (from Org Admin → Settings)"
  prompt        GATEWAY_DOMAIN   "Public hostname for this gateway (must resolve to this box)" "gateway.$(hostname -f 2>/dev/null | cut -d. -f2-).local"
  prompt        CADDY_ACME_EMAIL "Email for Let's Encrypt certificates" "admin@${GATEWAY_DOMAIN#gateway.}"
  prompt        ALLOWED_ORIGIN   "Browser origin allowed to call this gateway" "https://app.inchambers.ai"
  prompt_secret OPENROUTER_API_KEY "OpenRouter API key (optional — hit Enter to skip)" || true
  echo

  GATEWAY_MASTER_KEY="$(openssl rand -base64 32)"
  LITELLM_MASTER_KEY="sk-$(openssl rand -hex 24)"
  PG_PASSWORD="$(openssl rand -base64 24 | tr -d '=+/' | cut -c1-24)"
  hint "generated 32-byte master key"
  hint "generated LiteLLM admin key"
  hint "generated random Postgres password"
}

# ─── Install ───────────────────────────────────────────────────────────────
fetch_compose_files() {
  log "Fetching compose bundle to ${INSTALL_DIR}"
  sudo mkdir -p "${INSTALL_DIR}/caddy"
  sudo chown "$(id -u):$(id -g)" "${INSTALL_DIR}" "${INSTALL_DIR}/caddy"

  local files=(
    "deploy/docker-compose/docker-compose.yaml"
    "caddy/Caddyfile"
    "caddy/Caddyfile.notls"
  )
  for f in "${files[@]}"; do
    local out="${INSTALL_DIR}/${f#deploy/docker-compose/}"
    # Flatten: put Caddyfile/Caddyfile.notls under ./caddy/ relative to compose
    mkdir -p "$(dirname "$out")"
    curl -fsSL "${REPO_RAW}/${f}" -o "$out" || die "failed to fetch ${f}"
  done
}

write_env() {
  log "Writing ${INSTALL_DIR}/.env"
  umask 077
  cat > "${INSTALL_DIR}/.env" <<EOF
# Generated by install.sh on $(date -u +%FT%TZ) — do not commit.
GATEWAY_ORG_ID=${GATEWAY_ORG_ID}
GATEWAY_DOMAIN=${GATEWAY_DOMAIN}
CADDY_ACME_EMAIL=${CADDY_ACME_EMAIL}
ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
GATEWAY_MASTER_KEY=${GATEWAY_MASTER_KEY}
LITELLM_MASTER_KEY=${LITELLM_MASTER_KEY}
PG_PASSWORD=${PG_PASSWORD}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
REGISTRY=${IMAGE_REGISTRY}
IMAGE_TAG=${IMAGE_TAG}
CADDY_TLS_MODE=${CADDY_TLS_MODE:-internal}
EOF
  chmod 600 "${INSTALL_DIR}/.env"
}

boot() {
  log "Pulling images"
  ( cd "${INSTALL_DIR}" && docker compose pull )
  log "Starting the stack"
  ( cd "${INSTALL_DIR}" && docker compose up -d )
}

wait_healthy() {
  log "Waiting for the gateway to become reachable"
  local tries=0
  until curl -fsS --max-time 3 "http://localhost/health" >/dev/null 2>&1; do
    tries=$((tries + 1))
    if [[ $tries -gt 60 ]]; then
      warn "Gateway did not report healthy after 60s. Check 'docker compose logs' in ${INSTALL_DIR}."
      return 0
    fi
    sleep 1
  done
  log "${C_GREEN}Gateway is healthy.${C_RESET}"
}

print_next_steps() {
  cat <<EOF

  ${C_GREEN}${C_BOLD}inchambers-gateway is running.${C_RESET}

  Next steps:
    1. Point DNS: ${C_BOLD}${GATEWAY_DOMAIN}${C_RESET} → this host's public IP.
       (Until DNS propagates, Let's Encrypt will keep retrying.)

    2. In your inchambers.ai org admin dashboard:
         Settings → AI Platform → Gateway URL
       paste:  ${C_BOLD}https://${GATEWAY_DOMAIN}${C_RESET}

    3. Open the firm admin UI at:
         ${C_BOLD}https://${GATEWAY_DOMAIN}/admin/${C_RESET}
       Sign in with your inchambers.ai JWT (instructions on the page),
       then add ChatGPT Plus / Claude Pro cookies or your OpenRouter key.

  Files live at: ${INSTALL_DIR}
  Logs:          docker compose -f ${INSTALL_DIR}/docker-compose.yaml logs -f
  Stop:          docker compose -f ${INSTALL_DIR}/docker-compose.yaml down

EOF
}

main() {
  check_prereqs
  collect_inputs
  fetch_compose_files
  write_env
  boot
  wait_healthy
  print_next_steps
}

main "$@"
